//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitWrappers.System.Net.Mail {
    using System;
    using System.Net.Mail;
    
    
    public class SmtpClientWrap : IWrap<global::System.Net.Mail.SmtpClient>, ISmtpClient {
        
        private global::System.Net.Mail.SmtpClient _underlyingObject;
        
        public SmtpClientWrap(global::System.Net.Mail.SmtpClient underlyingObject) {
            this._underlyingObject = underlyingObject;
        }
        
        public SmtpClientWrap() {
            this._underlyingObject = new global::System.Net.Mail.SmtpClient();
        }
        
        public SmtpClientWrap(string host) {
            this._underlyingObject = new global::System.Net.Mail.SmtpClient(host);
        }
        
        public SmtpClientWrap(string host, int port) {
            this._underlyingObject = new global::System.Net.Mail.SmtpClient(host, port);
        }
        
        global::System.Net.Mail.SmtpClient IWrap<global::System.Net.Mail.SmtpClient>.UnderlyingObject {
            get {
                return this._underlyingObject;
            }
        }
    }
    
    public interface ISmtpClient {
    }
}
